solve:
	python ../instal/pysolve.py -i test7.ial -q query.lp -d domain.idc -t 5 -o ps-out.lp > output.txt
stream:
	python ../instal/pystream.py -i test7.ial -q query.lp -d domain.idc -t 5 -o ps-out.lp > output.txt
